Feat create graphql client
learn49/experiments pull request #15
Opened 2022-07-08 12:57 UTC by hugodnpm

#3 
Added and config urql.
Added .env-example

2022-07-10 00:55 UTC, RenatoSiqueira requested changes

2022-07-10 00:55 UTC, RenatoSiqueira commented on pages/_app.tsx
> +//  </AccountProvider>
Dead code. Why?

2022-07-10 00:58 UTC, RenatoSiqueira requested changes

2022-07-10 00:58 UTC, RenatoSiqueira commented on pages/[slug]/index.tsx
> +          <a>hugo-About</a>
Remove this names, please :D

2022-07-10 01:00 UTC, RenatoSiqueira commented
Please, resolve conflicts above

2022-07-10 22:32 UTC, hugodnpm commented on pages/_app.tsx
> +//  </AccountProvider>
I'm sorry, removed

2022-07-10 22:33 UTC, hugodnpm commented on pages/[slug]/index.tsx
> +          <a>hugo-About</a>
Ok! Removed

2022-07-11 01:52 UTC, RenatoSiqueira approved these changes

2022-07-12 00:40 UTC, merged